#lang racket
(displayln "Este programa imprime la suma de los números anteriores al número que el usuario ingrese")
(printf "Ingrese un número: ")
(define n (read))
(define (Interfaz)
(define (Number n start sum)
  (if (and(> n start)(not(= start (- n 1))))
      (begin
        (printf "~a+" start)
        (Number n (+ start 1)(+ start sum))
      )
       (if(or(= n )(- n 1))
         (printf "~a=~a" start (+ start sum))
         (void)
      )
  )
 )
(Number n 1 0))
(if (and(number? n)(positive? n)(integer? n))
    (Interfaz)
    (printf "El número ingresado no es válido, ingrese otro")
)
